# inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  Exclude:
    - bin/*
    - Gemfile

# Style/StringLiterals:
#   Exclude:
#     - config/*.rb
#     - config/environments/*.rb
#     - config/initializers/*.rb